export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const RESET_AUTH = 'RESET_AUTH';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const REMOVE_REFRESH_TOKEN = 'REMOVE_REFRESH_TOKEN';
export const SET_TOKEN_EXPIRATION = 'SET_TOKEN_EXPIRATION';
